Fixes error where getLoadOnlyIRIPrefix is null
Was getting the following error:
java.lang.NullPointerException: Cannot invoke "String.length()"
because "prefix" is null